### ISSUE TITLE
Hide and Seek

### ISSUE THREAD

**Issue by Sajeelzafar** [Sajeelzafar/Personal-Portfolio#13]
### In this issue, some intentional bugs are placed in order to be fixed.

**Comment by ManarOmari** [comment]
Good Job so far 👋 
I think you have to change lines" 66 and 83" in pop-up window.js [ the command "window.open(projectdetails[0].livesource);] to 
 [" window.open(projectdetails[0].livesource, "_blank");] to open them in new tabs.

**Comment by Sajeelzafar** [comment]
You have identified the bugs correctly, I've rectified the mistakes to carry on with the project.
